# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/justinkwinecki/Documents/Programming/Term_25-26/comp/ai_compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/justinkwinecki/Documents/Programming/Term_25-26/comp/ai_compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/justinkwinecki/Documents/Programming/Term_25-26/comp/ai_compiler/CMakeFiles /Users/justinkwinecki/Documents/Programming/Term_25-26/comp/ai_compiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/justinkwinecki/Documents/Programming/Term_25-26/comp/ai_compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dlc

# Build rule for target.
dlc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dlc
.PHONY : dlc

# fast build rule for target.
dlc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/build
.PHONY : dlc/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

src/codegen/add_emitter.o: src/codegen/add_emitter.cpp.o
.PHONY : src/codegen/add_emitter.o

# target to build an object file
src/codegen/add_emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/add_emitter.cpp.o
.PHONY : src/codegen/add_emitter.cpp.o

src/codegen/add_emitter.i: src/codegen/add_emitter.cpp.i
.PHONY : src/codegen/add_emitter.i

# target to preprocess a source file
src/codegen/add_emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/add_emitter.cpp.i
.PHONY : src/codegen/add_emitter.cpp.i

src/codegen/add_emitter.s: src/codegen/add_emitter.cpp.s
.PHONY : src/codegen/add_emitter.s

# target to generate assembly for a file
src/codegen/add_emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/add_emitter.cpp.s
.PHONY : src/codegen/add_emitter.cpp.s

src/codegen/add_relu_emitter.o: src/codegen/add_relu_emitter.cpp.o
.PHONY : src/codegen/add_relu_emitter.o

# target to build an object file
src/codegen/add_relu_emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/add_relu_emitter.cpp.o
.PHONY : src/codegen/add_relu_emitter.cpp.o

src/codegen/add_relu_emitter.i: src/codegen/add_relu_emitter.cpp.i
.PHONY : src/codegen/add_relu_emitter.i

# target to preprocess a source file
src/codegen/add_relu_emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/add_relu_emitter.cpp.i
.PHONY : src/codegen/add_relu_emitter.cpp.i

src/codegen/add_relu_emitter.s: src/codegen/add_relu_emitter.cpp.s
.PHONY : src/codegen/add_relu_emitter.s

# target to generate assembly for a file
src/codegen/add_relu_emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/add_relu_emitter.cpp.s
.PHONY : src/codegen/add_relu_emitter.cpp.s

src/codegen/codegen.o: src/codegen/codegen.cpp.o
.PHONY : src/codegen/codegen.o

# target to build an object file
src/codegen/codegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/codegen.cpp.o
.PHONY : src/codegen/codegen.cpp.o

src/codegen/codegen.i: src/codegen/codegen.cpp.i
.PHONY : src/codegen/codegen.i

# target to preprocess a source file
src/codegen/codegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/codegen.cpp.i
.PHONY : src/codegen/codegen.cpp.i

src/codegen/codegen.s: src/codegen/codegen.cpp.s
.PHONY : src/codegen/codegen.s

# target to generate assembly for a file
src/codegen/codegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/codegen.cpp.s
.PHONY : src/codegen/codegen.cpp.s

src/codegen/emitter.o: src/codegen/emitter.cpp.o
.PHONY : src/codegen/emitter.o

# target to build an object file
src/codegen/emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/emitter.cpp.o
.PHONY : src/codegen/emitter.cpp.o

src/codegen/emitter.i: src/codegen/emitter.cpp.i
.PHONY : src/codegen/emitter.i

# target to preprocess a source file
src/codegen/emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/emitter.cpp.i
.PHONY : src/codegen/emitter.cpp.i

src/codegen/emitter.s: src/codegen/emitter.cpp.s
.PHONY : src/codegen/emitter.s

# target to generate assembly for a file
src/codegen/emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/emitter.cpp.s
.PHONY : src/codegen/emitter.cpp.s

src/codegen/fully_connected_emitter.o: src/codegen/fully_connected_emitter.cpp.o
.PHONY : src/codegen/fully_connected_emitter.o

# target to build an object file
src/codegen/fully_connected_emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/fully_connected_emitter.cpp.o
.PHONY : src/codegen/fully_connected_emitter.cpp.o

src/codegen/fully_connected_emitter.i: src/codegen/fully_connected_emitter.cpp.i
.PHONY : src/codegen/fully_connected_emitter.i

# target to preprocess a source file
src/codegen/fully_connected_emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/fully_connected_emitter.cpp.i
.PHONY : src/codegen/fully_connected_emitter.cpp.i

src/codegen/fully_connected_emitter.s: src/codegen/fully_connected_emitter.cpp.s
.PHONY : src/codegen/fully_connected_emitter.s

# target to generate assembly for a file
src/codegen/fully_connected_emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/fully_connected_emitter.cpp.s
.PHONY : src/codegen/fully_connected_emitter.cpp.s

src/codegen/matmul_emitter.o: src/codegen/matmul_emitter.cpp.o
.PHONY : src/codegen/matmul_emitter.o

# target to build an object file
src/codegen/matmul_emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/matmul_emitter.cpp.o
.PHONY : src/codegen/matmul_emitter.cpp.o

src/codegen/matmul_emitter.i: src/codegen/matmul_emitter.cpp.i
.PHONY : src/codegen/matmul_emitter.i

# target to preprocess a source file
src/codegen/matmul_emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/matmul_emitter.cpp.i
.PHONY : src/codegen/matmul_emitter.cpp.i

src/codegen/matmul_emitter.s: src/codegen/matmul_emitter.cpp.s
.PHONY : src/codegen/matmul_emitter.s

# target to generate assembly for a file
src/codegen/matmul_emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/matmul_emitter.cpp.s
.PHONY : src/codegen/matmul_emitter.cpp.s

src/codegen/maxpool_emitter.o: src/codegen/maxpool_emitter.cpp.o
.PHONY : src/codegen/maxpool_emitter.o

# target to build an object file
src/codegen/maxpool_emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/maxpool_emitter.cpp.o
.PHONY : src/codegen/maxpool_emitter.cpp.o

src/codegen/maxpool_emitter.i: src/codegen/maxpool_emitter.cpp.i
.PHONY : src/codegen/maxpool_emitter.i

# target to preprocess a source file
src/codegen/maxpool_emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/maxpool_emitter.cpp.i
.PHONY : src/codegen/maxpool_emitter.cpp.i

src/codegen/maxpool_emitter.s: src/codegen/maxpool_emitter.cpp.s
.PHONY : src/codegen/maxpool_emitter.s

# target to generate assembly for a file
src/codegen/maxpool_emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/maxpool_emitter.cpp.s
.PHONY : src/codegen/maxpool_emitter.cpp.s

src/codegen/relu_emitter.o: src/codegen/relu_emitter.cpp.o
.PHONY : src/codegen/relu_emitter.o

# target to build an object file
src/codegen/relu_emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/relu_emitter.cpp.o
.PHONY : src/codegen/relu_emitter.cpp.o

src/codegen/relu_emitter.i: src/codegen/relu_emitter.cpp.i
.PHONY : src/codegen/relu_emitter.i

# target to preprocess a source file
src/codegen/relu_emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/relu_emitter.cpp.i
.PHONY : src/codegen/relu_emitter.cpp.i

src/codegen/relu_emitter.s: src/codegen/relu_emitter.cpp.s
.PHONY : src/codegen/relu_emitter.s

# target to generate assembly for a file
src/codegen/relu_emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/relu_emitter.cpp.s
.PHONY : src/codegen/relu_emitter.cpp.s

src/codegen/sub_emitter.o: src/codegen/sub_emitter.cpp.o
.PHONY : src/codegen/sub_emitter.o

# target to build an object file
src/codegen/sub_emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/sub_emitter.cpp.o
.PHONY : src/codegen/sub_emitter.cpp.o

src/codegen/sub_emitter.i: src/codegen/sub_emitter.cpp.i
.PHONY : src/codegen/sub_emitter.i

# target to preprocess a source file
src/codegen/sub_emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/sub_emitter.cpp.i
.PHONY : src/codegen/sub_emitter.cpp.i

src/codegen/sub_emitter.s: src/codegen/sub_emitter.cpp.s
.PHONY : src/codegen/sub_emitter.s

# target to generate assembly for a file
src/codegen/sub_emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/codegen/sub_emitter.cpp.s
.PHONY : src/codegen/sub_emitter.cpp.s

src/ir/graph.o: src/ir/graph.cpp.o
.PHONY : src/ir/graph.o

# target to build an object file
src/ir/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/ir/graph.cpp.o
.PHONY : src/ir/graph.cpp.o

src/ir/graph.i: src/ir/graph.cpp.i
.PHONY : src/ir/graph.i

# target to preprocess a source file
src/ir/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/ir/graph.cpp.i
.PHONY : src/ir/graph.cpp.i

src/ir/graph.s: src/ir/graph.cpp.s
.PHONY : src/ir/graph.s

# target to generate assembly for a file
src/ir/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/ir/graph.cpp.s
.PHONY : src/ir/graph.cpp.s

src/ir/graph_builder.o: src/ir/graph_builder.cpp.o
.PHONY : src/ir/graph_builder.o

# target to build an object file
src/ir/graph_builder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/ir/graph_builder.cpp.o
.PHONY : src/ir/graph_builder.cpp.o

src/ir/graph_builder.i: src/ir/graph_builder.cpp.i
.PHONY : src/ir/graph_builder.i

# target to preprocess a source file
src/ir/graph_builder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/ir/graph_builder.cpp.i
.PHONY : src/ir/graph_builder.cpp.i

src/ir/graph_builder.s: src/ir/graph_builder.cpp.s
.PHONY : src/ir/graph_builder.s

# target to generate assembly for a file
src/ir/graph_builder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/ir/graph_builder.cpp.s
.PHONY : src/ir/graph_builder.cpp.s

src/ir/tensor.o: src/ir/tensor.cpp.o
.PHONY : src/ir/tensor.o

# target to build an object file
src/ir/tensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/ir/tensor.cpp.o
.PHONY : src/ir/tensor.cpp.o

src/ir/tensor.i: src/ir/tensor.cpp.i
.PHONY : src/ir/tensor.i

# target to preprocess a source file
src/ir/tensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/ir/tensor.cpp.i
.PHONY : src/ir/tensor.cpp.i

src/ir/tensor.s: src/ir/tensor.cpp.s
.PHONY : src/ir/tensor.s

# target to generate assembly for a file
src/ir/tensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/ir/tensor.cpp.s
.PHONY : src/ir/tensor.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/optimizer/optimizer.o: src/optimizer/optimizer.cpp.o
.PHONY : src/optimizer/optimizer.o

# target to build an object file
src/optimizer/optimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/optimizer/optimizer.cpp.o
.PHONY : src/optimizer/optimizer.cpp.o

src/optimizer/optimizer.i: src/optimizer/optimizer.cpp.i
.PHONY : src/optimizer/optimizer.i

# target to preprocess a source file
src/optimizer/optimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/optimizer/optimizer.cpp.i
.PHONY : src/optimizer/optimizer.cpp.i

src/optimizer/optimizer.s: src/optimizer/optimizer.cpp.s
.PHONY : src/optimizer/optimizer.s

# target to generate assembly for a file
src/optimizer/optimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/optimizer/optimizer.cpp.s
.PHONY : src/optimizer/optimizer.cpp.s

src/utils/algorithms.o: src/utils/algorithms.cpp.o
.PHONY : src/utils/algorithms.o

# target to build an object file
src/utils/algorithms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/utils/algorithms.cpp.o
.PHONY : src/utils/algorithms.cpp.o

src/utils/algorithms.i: src/utils/algorithms.cpp.i
.PHONY : src/utils/algorithms.i

# target to preprocess a source file
src/utils/algorithms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/utils/algorithms.cpp.i
.PHONY : src/utils/algorithms.cpp.i

src/utils/algorithms.s: src/utils/algorithms.cpp.s
.PHONY : src/utils/algorithms.s

# target to generate assembly for a file
src/utils/algorithms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/utils/algorithms.cpp.s
.PHONY : src/utils/algorithms.cpp.s

src/utils/json_parser.o: src/utils/json_parser.cpp.o
.PHONY : src/utils/json_parser.o

# target to build an object file
src/utils/json_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/utils/json_parser.cpp.o
.PHONY : src/utils/json_parser.cpp.o

src/utils/json_parser.i: src/utils/json_parser.cpp.i
.PHONY : src/utils/json_parser.i

# target to preprocess a source file
src/utils/json_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/utils/json_parser.cpp.i
.PHONY : src/utils/json_parser.cpp.i

src/utils/json_parser.s: src/utils/json_parser.cpp.s
.PHONY : src/utils/json_parser.s

# target to generate assembly for a file
src/utils/json_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/utils/json_parser.cpp.s
.PHONY : src/utils/json_parser.cpp.s

src/utils/logger.o: src/utils/logger.cpp.o
.PHONY : src/utils/logger.o

# target to build an object file
src/utils/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/utils/logger.cpp.o
.PHONY : src/utils/logger.cpp.o

src/utils/logger.i: src/utils/logger.cpp.i
.PHONY : src/utils/logger.i

# target to preprocess a source file
src/utils/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/utils/logger.cpp.i
.PHONY : src/utils/logger.cpp.i

src/utils/logger.s: src/utils/logger.cpp.s
.PHONY : src/utils/logger.s

# target to generate assembly for a file
src/utils/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dlc.dir/build.make CMakeFiles/dlc.dir/src/utils/logger.cpp.s
.PHONY : src/utils/logger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... format"
	@echo "... dlc"
	@echo "... src/codegen/add_emitter.o"
	@echo "... src/codegen/add_emitter.i"
	@echo "... src/codegen/add_emitter.s"
	@echo "... src/codegen/add_relu_emitter.o"
	@echo "... src/codegen/add_relu_emitter.i"
	@echo "... src/codegen/add_relu_emitter.s"
	@echo "... src/codegen/codegen.o"
	@echo "... src/codegen/codegen.i"
	@echo "... src/codegen/codegen.s"
	@echo "... src/codegen/emitter.o"
	@echo "... src/codegen/emitter.i"
	@echo "... src/codegen/emitter.s"
	@echo "... src/codegen/fully_connected_emitter.o"
	@echo "... src/codegen/fully_connected_emitter.i"
	@echo "... src/codegen/fully_connected_emitter.s"
	@echo "... src/codegen/matmul_emitter.o"
	@echo "... src/codegen/matmul_emitter.i"
	@echo "... src/codegen/matmul_emitter.s"
	@echo "... src/codegen/maxpool_emitter.o"
	@echo "... src/codegen/maxpool_emitter.i"
	@echo "... src/codegen/maxpool_emitter.s"
	@echo "... src/codegen/relu_emitter.o"
	@echo "... src/codegen/relu_emitter.i"
	@echo "... src/codegen/relu_emitter.s"
	@echo "... src/codegen/sub_emitter.o"
	@echo "... src/codegen/sub_emitter.i"
	@echo "... src/codegen/sub_emitter.s"
	@echo "... src/ir/graph.o"
	@echo "... src/ir/graph.i"
	@echo "... src/ir/graph.s"
	@echo "... src/ir/graph_builder.o"
	@echo "... src/ir/graph_builder.i"
	@echo "... src/ir/graph_builder.s"
	@echo "... src/ir/tensor.o"
	@echo "... src/ir/tensor.i"
	@echo "... src/ir/tensor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/optimizer/optimizer.o"
	@echo "... src/optimizer/optimizer.i"
	@echo "... src/optimizer/optimizer.s"
	@echo "... src/utils/algorithms.o"
	@echo "... src/utils/algorithms.i"
	@echo "... src/utils/algorithms.s"
	@echo "... src/utils/json_parser.o"
	@echo "... src/utils/json_parser.i"
	@echo "... src/utils/json_parser.s"
	@echo "... src/utils/logger.o"
	@echo "... src/utils/logger.i"
	@echo "... src/utils/logger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

